
 
# - name: Print redis
#   debug:
#      msg: redis


- name: Install redis
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed

- name: Enable  & Install redis
  ansible.builtin.dnf:
    name: "@redis:remi-6.2"
    state: installed

