

# print_head "Enable Mongodb"
# systemctl enable mongod  &>>${log_file}
# status_check $?

# print_head "Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf"
# sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf &>>${log_file}
# status_check $?


# print_head "start Mongodb"  
# systemctl restart mongod &>>${log_file}
# status_check $?

- name: Setup Mongodb Repo
  ansible.builtin.copy:
    src: mongodb.repo
    state: /etc/yum.repos.d/mongo.repo
    

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed


- name: Update listen address from 127.0.0.1 to 0.0.0.0 
  ansible.builtin.replace:
    path: etc/mongod.conf
    regexp: '127.0.0.1'
    repalce: '0.0.0.0'

- name: start mongodb
  ansible.builtin.systemdb:
    name: mongodb
    state: started
    enable: yes