- name: Setup Mongodb Repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo
    

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: latest


# - name: Update listen address from 127.0.0.1 to 0.0.0.0 
#   ansible.builtin.replace:
#     path: etc/mongod.conf
#     regexp: '127.0.0.1'
#     repalce: '0.0.0.0'

# - name: start mongodb
#   ansible.builtin.systemdb:
#     name: mongodb
#     state: started
#     enable: yes