
 
# - name: Print mongodb
#   debug:
#      msg: mongodb


- name: Setup Mongodb repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo


- name: Install Mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update Mongodb Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    repalce: '0.0.0.0'

- name: Start mongodb
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: true
