
- name: Setupt Erlang Repos
  ansible.builtin.shell: curl -s  https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash


- name: Install rabitmq Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash


- name: Install Erlang and rabitmq
  ansible.builtin.yum:
    name:
      - rabbitmq-server
      - erlang
    start: installed


- name: start Rabbitmq service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes


- name: Add appliaction User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present