
# - name: Print rabbitmq
#   debug:
#      msg: rabbitmq


- name: Setup erlang Repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Install Rabitmq Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install Erlang and Rabitmq
  ansible.builtin.yum:
    name:
      - rabbitmq-server
      - erlang
    state: installed  

- name: start Rabitmq service
  ansible.builtin.systemd:
     name: rabbitmq-server
     state: started
     enabled: true


- name: Add App user
  community.rabbitmq.rabbitmq_user:
     user: roboshop
     password: roboshop123
     vhost: /
     configure_prive: .*
     read_prive: .*
     write_prive: .*
     state: present
  
