
  # print_head "install maven"
  # yum install maven -y  &>>${log_file}
  # status_check $?
  
  # app-prepreq.yml
  
  # print_head "download dependency & packages"
  # mvn clean package   &>>${log_file}
  # mv target/${component}-1.0.jar ${component}.jar  &>>${log_file}
  # status_check $?
  

  # # schema setup function
  # schema_type
  
  # #b systemd function
  # systemd_setup



# - name: Install Maven
#   ansible.builtin.yum:
#     name: maven
#     state: installed

# - name: app-prepreq 
#   ansible.builtin.import_tasks:
#     file: app-prepreq.yml


# - name: Install Maven Dependency
#   ansible.builtin.shell:  mvn clean package; mv target/{{component}}-1.0.jar {{component}}.jar
#   args:
#       chdir: /app

# - name: schema_setup
#   ansible.builtin.import_tasks:
#     file: schema_setup.yml
#   when: schema_type is defined

# - name: systemd-setup
#   ansible.builtin.import_tasks:
#     file: systemd_setup.yml





- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: app_prereq_setup
  ansible.builtin.import_tasks:
    file: app-prepreq.yml


- name: Install Maven Dependency
  ansible.builtin.shell:  mvn clean package; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
      chdir: /app

- name: schema_setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml
  when: schema_type is defined

- name: systemd-setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml

