

# schema_type() {
# if  [ "${schema_type}" == "mongo" ]; then
#     print_head "Copy MongoDB Repo File"
#     cp ${code_dir}/configs/mongodb.repo /etc/yum.repos.d/mongodb.repo &>>${log_file}
#     status_check $?

#     print_head "Install Mongo Client"
#     yum install mongodb-org-shell -y &>>${log_file}
#     status_check $?

#     print_head "Load Schema"
#     mongo --host mongodb-dev.devsig90.online </app/schema/${component}.js &>>${log_file}
#     status_check $?
# elif  [ "${schema_type}" == "mysql" ]; then
#     print_head "Install MySQL Client"
#     yum install mysql -y &>>${log_file}
#     status_check $?

#     print_head "Load Schema"
#     mysql -h mysql-dev.devsig90.online -uroot -p${mysql_root_password} < /app/schema/shipping.sql &>>${log_file}
#     status_check $?
# fi

- name: MogoDB schema
  when: schema_type == "mongo"
  block:
    - name: Copy MongoDB Repo File
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo
    


    - name: Install MongoDB Client"
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mongo --host mongodb-dev.devsig90.online </app/schema/{{ component }}.js



- name: MYSQL schema
  when: schema_typ == "mysql"
  block:
    - name: Install MySQL Client
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load Schema
      ansible.builtin.shell: mysql -h mysql-dev.devsig90.online -uroot -pRoboShop@1 < /app/schema/{{ component }}.sql
      

